dist: trusty
language:
  - cpp
  - python
compiler: gcc
python: "3.5"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - g++-4.8
      - python3.5-dev

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/1.0.0/bazel_1.0.0-linux-x86_64.deb
  - sudo dpkg -i bazel_1.0.0-linux-x86_64.deb

script:
  - tools/buildall.sh
